### ISSUE TITLE
[HIGH RISK] This repo is infected by XCSSET Malware 

### ISSUE THREAD

**Issue by alokc83** [RobotsAndPencils/XcodesApp#139]
**Describe the bug**
I used this repo last week at work. Today I was shut down by IT team saying that this Malware is found on this system. 
Please check this repo thoroughly as I believe this malware was due to this infected project

**Comment by MattKiazyk** [comment]
Hi @alokc83 Thanks for the issue. I've investigated and couldn't find anything that would indicate that to be true. If your IT department has any more information that they would like to pass on, please do so. 

Xcodes does use a privileged helper that requires higher privileges in order to install the Xcode Versions. You can see what it's doing here https://github.com/RobotsAndPencils/XcodesApp/blob/main/Xcodes/Backend/HelperClient.swift#L41 That helper client is a XPC service (https://developer.apple.com/documentation/xpc) that allows Xcodes to perform the work it needs to (download, unxip, copy, xcode-select) 

I can see how your IT department would perhaps indicate that as Malware, as you are basically giving Xcodes the ability to install anything.

I'm going to close this issue, but let us know if there's anything else we can do to help remedy your IT Departments concerns.
