### ISSUE TITLE
Xcodes silently fails on all contextual options only with Xcode 13 RC

### ISSUE THREAD

**Issue by kiliankoe** [RobotsAndPencils/XcodesApp#154]
**Describe the bug**
@oliverepper and I have just run into the weirdest issue (on two separate Macs), where all contextual actions (Reveal in Finder, Copy Path, Make active in the sidebar) don't appear to be working for Xcode 13.0 (13A233), but interestingly enough only on this specific version of Xcode. Everything works just as expected on Xcode 13.0 Beta 5 (13A5212g). 

The xcodes CLI doesn't have this issue and can select Xcode 13 RC as the active installation.

**To Reproduce**
- Right click on Xcode 13 RC in XcodesApp
- Choose Reveal in Finder
- Nothing happens

**Version**
 - OS: 11.4 (20F71)
 - Xcodes: 1.1.0 (7)

**Comment by MattKiazyk** [comment]
Hi @kiliankoe thanks for the bug.

So the issue is that the 13.0 RC build is the identical build to 13.0, and Xcodes now takes 13.0 as the "Default" 13.0 build. 

If it was the same as mine, and you downloaded the 13.0 RC version, you'll notice the path:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1119565/134351287-741e92af-a682-4c6f-a10b-3f18a391298c.png">

Xcode now thinks though that the 13.0 version should be at `Xcode-13.0.0.app` and the open or show in finder doesn't work.

As a workaround, simply rename your Xcode version to `Xcode-13.0.0`, Hit refresh, and things should start working again.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1119565/134351819-573bc7d1-1d41-4416-a54c-83065d8f8a83.png">

If that doesn't work, please let me know.

**Comment by kiliankoe** [comment]
Hey @MattKiazyk! Thanks, that totally worked. I saw that the build was the same, but didn't realize that Xcodes had already updated the metadata and listed Xcode 13.0 instead of the RC 🙈 

I'm going to go ahead and close this then, thanks!
