### ISSUE TITLE
Can't install Xcode version 13.1

### ISSUE THREAD

**Issue by khorbushko** [RobotsAndPencils/XcodesApp#173]
**Describe the bug**
Can't install Xcode version 13.1 after 13.2 installed

**To Reproduce**
1. start app
2. press install button
3. see popUp with err

**Expected behavior**
Installation started

**Screenshots**
<img width="1012" alt="Знімок екрана 2021-12-14 о 23 22 23" src="https://user-images.githubusercontent.com/8652224/146081286-dd94d855-1351-4bb2-a13a-e8cf8690c7a3.png">

**Version**
 - OS: 12.0.1 (21A559)
 - Xcodes: 13.2

**Comment by StefaniOSApps** [comment]
same on 12.5.1

<img width="1118" alt="Bildschirmfoto 2021-12-14 um 23 30 03" src="https://user-images.githubusercontent.com/29314643/146090091-b1f242a9-56de-4d27-b318-438ae55b17a7.png">

**Comment by MattKiazyk** [comment]
@StefaniOSApps @khorbushko if any of you have a proxy (ex Charles), can you send me which call is getting invalid json?

**Comment by jacobbullock** [comment]
This was failing for me, but when I forked the repo and started to play with it locally, it gave me the proper error message that I wasn't signed in.  I went back to the downloaded version and signed in with apple and then no more issue downloading.  The latest code in the main branch seems to work fine, so maybe need to do another release for installation via brew?  The last release shows Oct 22, but main has changes since then.

**Comment by MattKiazyk** [comment]
Thanks for the validation @jacobbullock that the code changes in master are working. I'll try to get a release out soon.

**Comment by EmirTola** [comment]
I just had the same issue, fresh install of Xcodes via homebrew resulted in above error. Signing in fixed it.

**Comment by muhasturk** [comment]
@MattKiazyk could you please fire new release as soon as possible?

**Comment by bitcrumb** [comment]
I had the same issue on the latest release of Xcodes app (v1.2.0).

So I reverted to the version before that (v1.1.0), and the issue did not occur.

If this is indeed not an issue on master as reported here, could a new release be issues? Especially since v1.2.0 is also showing another high-visibility bug (with incorrect developer account requirement).

Thanks!

**Comment by phalgun** [comment]
had the same issue, logged in to my Apple account first and then this was resolved. 
Would be nice to mention this somewhere as the app onboarding did not mention anything about needing to login.

**Comment by phalgun** [comment]
had the same issue, logged in to my Apple account first and then this was resolved. 
Would be nice to mention this somewhere as the app onboarding did not mention anything about needing to login.

**Comment by MattKiazyk** [comment]
Closing this issue since 1.3.1 tackles a lot of issues around json parsing. If there's other issues, please create a new issues. Thanks!
