### ISSUE TITLE
Question for Robots and Pencils, why isn't this app published?

### ISSUE THREAD

**Issue by michael94ellis** [RobotsAndPencils/XcodesApp#187]
I think this would awesome to use for work but first I would need to go through the code to comply with my companies guidelines and policies. 

I looked briefly for an answer and didn't find one. Why isn't this published on the app store?

**Comment by lukemmtt** [comment]
I'm not a contributor to XcodesApp, but I can offer a guess as to why it hasn't been published to the Mac App Store: Doing so would require significantly more effort for little gain, and this project's core function is very likely against Apple's terms of service.

Apps that are submitted to the Mac App Store are subject to much more restrictions and scrutiny than self-published apps. By default, Mac App Store apps are "sandboxed" and have little ability to manipulate things beyond their bounds.

It may be possible to overcome some of these restrictions with specific entitlements, but even then, I'd be amazed if this app  would ever make it through App Review, because the very premise of this application (software that allows users to install other software) is antithetical to what the Mac App Store is all about. 

More info:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html
https://www.appcoda.com/mac-app-sandbox/

**Comment by MattKiazyk** [comment]
@michael94ellis thanks for the question, sorry for the late response.

@lukemmtt is spot on with the comments. While I don't think it's against Apple's terms of service (we are just using their api's), we are working around the crappy experience of the Mac App Store when installing Xcode. 

It has been thought about, and perhaps one day, but as stated, the gains of being more public in the AppStore is outweighed by the effort needed to get there. We also want to keep the code public so that developers understand what we are doing, and how we are doing it.
