### ISSUE TITLE
[Bug] extension point errors for some command line tools and xcodebuild

### ISSUE THREAD

**Issue by andrewcrook** [RobotsAndPencils/XcodesApp#254]
**Describe the bug**
running some command-line tools such as `man` and `xcodebuild` results in the following errors.

```sh
2022-06-14 14:46:52.530 xcodebuild[33523:224173] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

2022-06-14 14:46:52.530 xcodebuild[33523:224173] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

**To Reproduce**
`xcodebuild`

**Expected behavior**
No errors

**Screenshots**
```
xcode-select -p
/Applications/Xcode-13.4.1.app/Contents/Developer
```

*** Other info ***
I have searched online people talk about installing commandline tools via
`xcode-select --install`
This installs into ` /Library/Developer/CommandLineTools`
However, Xcode’s Xcode installs setup in `/Applications/Xcode-xx.x.x.app/Contents/Developer`
Which looks correct to me because you want the version of command tools to go with the version of Xcode.

![image](https://user-images.githubusercontent.com/803618/173595971-e09a675c-65ad-4eee-8af6-7b0826db9e35.png)

However, if I compare the contents of the two locations they are clearly different. 

```sh
ls  /Library/Developer/CommandLineTools 
Library SDKs    usr
```

```sh
 ls /Applications/Xcode-13.4.1.app/Contents/Developer
Applications Library      Makefiles    Platforms    Toolchains   Tools        usr
```

**Version**
 - OS: 12.4 (21F79) on M1 MBP
 - Xcodes: 1.6.0 (14)

**Comment by VaslD** [comment]
Those warnings are likely bugs from recent Xcode releases. I’ve seen them on M1 (Apple Silicon) Macs mostly, with Xcode installed via vanilla XIPs downloaded from Apple Developer Downloads (without using any third-party software in the process).

- - - - -

Also, Xcode (the app) has nothing to do with Xcode Command Line Tools (CLT) installed in `/Library/Developer`. They are independent.

CLT is more like a mini-Xcode that provides the basic UNIX build tool chain (for C/C++, Python, etc). Most third-party tools that rely on Xcode can run with only CLT installed, that is without having to depend on a 10 GB download. But since CLT is mini, it doesn’t contain all developing resources compared to a full Xcode install. So it’s normal that the two directories you listed were different.

**Comment by MattKiazyk** [comment]
Closing this as it should be in the https://github.com/RobotsAndPencils/xcodes repo. If it still is happening with please open an issue there. Thanks
