### ISSUE TITLE
Filter/info pane doesn't persist across app closes

### ISSUE THREAD

**Issue by MattKiazyk** [RobotsAndPencils/XcodesApp#71]
Issue:
If I tap on the filter or the info pane, it should persist across app loads

![image](https://user-images.githubusercontent.com/1119565/105243135-3de86700-5b34-11eb-8612-b63b86c7e894.png)

Repro Steps:
1. Set the filter on, or the info pane on
2. Close the app, reopen
3. App shows all versions again

This _was_ working previously.

**Comment by interstateone** [comment]
Okay this is weird, and feels like a bug with SceneStorage on macOS.

I have a minimal sample project to test this out, which matches what I see with Xcodes. If I stop the app with Xcode, or force quit or `killall`, the next launch will restore the SceneStorage state. If I quit the app normally (⌘-Q) and then re-run it with Xcode, it won't restore the state. This also happens when not running from Xcode, like with an archived build. Quit the app  and the next launch won't restore state.

What I'd expect to happen is for SceneStorage state to be restored in all of these situations.

---

> If the Scene is explictly destroyed (e.g. the switcher snapshot is destroyed on iPadOS or the window is closed on macOS), the data is also destroyed.

https://developer.apple.com/documentation/swiftui/scenestorage#

I wonder if it's not distinguishing between "window closed because window was closed by user" and "window closed because app was terminated by user"?

The behaviour also seems similar to this quote, which is for UIKit state restoration:

> When debugging the sample project, the system automatically deletes its preserved state when the user force quits the app. Deleting the preserved state information is a safety precaution. In addition, the system also deletes the preserved state if this app crashes at launch time. To test the sample app’s ability to restore the sample’s state, do not use the app switcher to force quit it during debugging. Instead, use Xcode to stop the app, or stop the app programmatically. One technique is to suspend the sample app using the Home button, and then stop the debugger in Xcode. Launch the sample app again using Xcode, and UIKit initiates the state restoration process.

https://developer.apple.com/documentation/uikit/uiviewcontroller/restoring_your_app_s_state

---

The easiest solution is probably to use AppStorage for now, with a comment explaining why. This _should be_ scene-specific state, but having them all use the same state is not a big deal since multiple windows is not really a desired situation.

**Comment by interstateone** [comment]
I've submitted feedback for this: FB8979533 "SceneStorage doesn't restore value after app is quit by user"
