### ISSUE TITLE
Identical builds aren't represented clearly

### ISSUE THREAD

**Issue by paulthorsteinson** [RobotsAndPencils/XcodesApp#90]
Hi!
I installed the app and ran it and noticed it was out of date as it didnt include 12.4 as my command line did
<img width="259" alt="Screen Shot 2021-01-28 at 8 46 56 AM" src="https://user-images.githubusercontent.com/331285/106163049-fc644700-6145-11eb-968b-5b13c614bd0a.png">
<img width="595" alt="Screen Shot 2021-01-28 at 8 48 56 AM" src="https://user-images.githubusercontent.com/331285/106163073-01c19180-6146-11eb-9a49-de9773d2836d.png">
I hit the refresh button and it did not show up.  Then I went to preferences and signed in, hit refresh, still nothing. Not sure why its missing the 12.4 release (not the RC)

**Comment by interstateone** [comment]
Hey Paul! 👋 Thanks for opening this issue.

Regarding Xcodes.app vs xcodes, they might not show exactly the same versions right now because they're using different data sources. Xcodes.app defaults to use Xcode Releases, and xcodes scrapes the Apple Developer site, but will be switching in the next release to [also default to Xcode Releases](https://github.com/RobotsAndPencils/xcodes/pull/129). In the future I would expect them to show the same data though.

Regarding 12.4 RC vs release, what you're seeing is actually deliberate but maybe not ideal. I'll explain why, and as a user you shouldn't have to care about these details, but I'm curious to get your thoughts on how this could be improved.

The 12.4 RC and 12.4 final releases are actually exactly the same build (12D4e), which is reflected in the [Xcode Releases](https://xcodereleases.com) data. This is not uncommon. I'd assumed that almost every user doesn't care about this, and would never want to install the same build twice with different names. Based on this assumption, when there are multiple versions with the same build identifier in the Xcode Releases data and one of them is a "release" version, we [only keep the release version](https://github.com/RobotsAndPencils/XcodesApp/blob/main/Xcodes/Backend/AppState+Update.swift#L211) as a result. xcodes would also do this once it uses Xcode Releases. Based on this, we'd expect to see Xcodes.app have one row for the release version of 12.4, but your screenshot instead has one row for 12.4 RC.

I think what might also be happening in your situation is that [some other code](https://github.com/RobotsAndPencils/XcodesApp/blob/main/Xcodes/Backend/AppState.swift#L429) is then replacing the release version of 12.4 that's available, and which wasn't filtered out, with the RC version that you have installed because they have the same build identifier. There were other reasons for this code, but in this case the result of showing the version you have installed and not showing the release version at all is definitely misleading.

I still don't think that we want to have two rows for 12.4 RC and 12.4 when they're the same build. I think most users, if they had 12.4 RC installed, would only want to know that the release version of 12.4 didn't change and that they can continue to use the version they already have. So maybe one way to improve this situation is to still only show the one row for 12.4 RC that you have installed, but also indicate somewhere in the row that this is the same as the release version of 12.4?

Let me know what you think.

**Comment by interstateone** [comment]
(Maybe the solution is: I'm overthinking it, just show two rows, users will see that the build identifiers are the same 😄)

**Comment by paulthorsteinson** [comment]
Thanks for the insight @interstateone!  I do think its important to distinguish if something is an actual release or not.  In this case, the Xcode's app shows 12.4 RC - when I see that I always think "I better check back in a few days in case they released a different version for the actual release".  While two rows would be a solution, that too is a bit weird as it make it seem as though they are two distinct builds.  One solution when there is an actual release and a RC that are one in the same, to default to using the non RC release name "12.4" but perhaps list matching builds somewhere (on the right??) Perhaps
Xcode 12.4 (12D4e)                                              Matching builds: (12.4 RC)

my two cents.  Thanks for making this!
